spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:mysql://localhost}
    username: ${JDBC_DATABASE_USERNAME:}
    password: ${JDBC_DATABASE_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    org:
      springframework: INFO

server:
  port: ${PORT:5000}
