spring:
  profiles:
    active: dev

  # Temporary Exclude DB Configuration
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration.class
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

blogapp:
  title: "BlogApp"
  subtitle: "Skillbox Graduation Work: Simple Blog Engine"
  phone: "+7 000 765-4321"
  email: "konstantin.ershov@gmail.com"
  copyright: "Konstantin Ershov"
  copyrightFrom: "2020"
