spring:
  profiles:
    active: dev
  datasource:
    url: ${JDBC_DATABASE_URL:}
    username: ${JDBC_DATABASE_USERNAME:}
    password: ${JDBC_DATABASE_PASSWORD:}
    driver-class-name: org.postgresql.Driver
    # Keep the connection alive if idle for a long time (needed in production)
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    # Show or not log for each sql query
    show-sql: true
    hibernate:
      # Hibernate ddl auto (create, create-drop, update): with "create-drop" the database
      # schema will be automatically created afresh for every start of application
      ddl-auto: create-drop
      # Naming strategy
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    # Allows Hibernate to generate SQL optimized for a particular DBMS
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  hikari:
    connection-timeout: 30000
    maximum-pool-size: 10
logging:
  level:
    org.springframework: INFO

blogapp:
  title: "BlogApp"
  subtitle: "Skillbox Graduation Work: Simple Blog Engine"
  phone: "+7 000 765-4321"
  email: "konstantin.ershov@gmail.com"
  copyright: "Konstantin Ershov"
  copyrightFrom: "2020"
