spring:
  profiles:
    active: dev
  datasource:
    url: ${JDBC_DATABASE_URL:}
    username: ${JDBC_DATABASE_USERNAME:}
    password: ${JDBC_DATABASE_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
    # Keep the connection alive if idle for a long time (needed in production)
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    # Show or not log for each sql query
    show-sql: true
    hibernate:
      # Hibernate ddl-auto:
      #   validate - validate the schema, makes no changes to the database.
      #   update - update the schema.
      #   create - creates the schema, destroying previous data.
      #   create-drop - drop the schema when the SessionFactory is closed explicitly, typically when the application is stopped.
      #   none - does nothing with the schema, makes no changes to the database
      ddl-auto: create
      # Naming strategy
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    # Allows Hibernate to generate SQL optimized for a particular DBMS
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  hikari:
    connection-timeout: 30000
    maximum-pool-size: 10
logging:
  level:
    org.springframework: INFO

blogapp:
  title: "BlogApp"
  subtitle: "Skillbox Graduation Work: Simple Blog Engine"
  phone: "+7 000 765-4321"
  email: "konstantin.ershov@gmail.com"
  copyright: "Konstantin Ershov"
  copyrightFrom: "2020"
  settings:
    MULTIUSER_MODE: false
    POST_PREMODERATION: true
    STATISTICS_IS_PUBLIC: true

